services:
  uta:
    # Test:
    # psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from uta_20241220.transcript'
    # 314227
    image: biocommons/uta:uta_20241220
    environment:
      - POSTGRES_PASSWORD=strong-password
    volumes:
      - uta_dl_cache:/tmp
      - uta_vol:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  uta_vol:
    external: true
  uta_dl_cache:
    external: true
